import { IMonthCard } from '../vip-preview/components/month-part'

// 主播合集商品数组
export const AnchorGoodsList: IMonthCard[] = [
  {
    goodsId: '黑珍',
    bgIMG: '/type/黑珍.png',
    title: '黑珍',
    price: 108,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/黑珍@108.png',
  },
  {
    goodsId: '娜娜',
    bgIMG: '/type/娜娜.png',
    title: '娜娜',
    price: 108,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/娜娜@108.png',
  },
  {
    goodsId: '孝卡',
    bgIMG: '/type/孝卡.png',
    title: '孝卡',
    price: 108,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/孝卡@108.png',
  },
  {
    goodsId: '贝拉',
    bgIMG: '/type/贝拉.png',
    title: '贝拉',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/贝拉@98.png',
  },
  {
    goodsId: '哈里米',
    bgIMG: '/type/哈里米.png',
    title: '哈里米',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/哈里米@98.png',
  },
  {
    goodsId: '慧明',
    bgIMG: '/type/慧明.png',
    title: '慧明',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/慧明@98.png',
  },
  {
    goodsId: '橘子',
    bgIMG: '/type/橘子.png',
    title: '橘子',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/橘子@98.png',
  },
  {
    goodsId: '牛奶',
    bgIMG: '/type/牛奶.png',
    title: '牛奶',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/牛奶@98.png',
  },
  {
    goodsId: '平腾',
    bgIMG: '/type/平腾.png',
    title: '平腾',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/平腾@98.png',
  },
  {
    goodsId: '奇瑞',
    bgIMG: '/type/奇瑞.png',
    title: '奇瑞',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/奇瑞@98.png',
  },
  {
    goodsId: '诗妍',
    bgIMG: '/type/诗妍.png',
    title: '诗妍',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/诗妍@98.png',
  },
  {
    goodsId: '世妍',
    bgIMG: '/type/世妍.png',
    title: '世妍',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/世妍@98.png',
  },
  {
    goodsId: '塔妮',
    bgIMG: '/type/塔妮.png',
    title: '塔妮',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/塔妮@98.png',
  },
  {
    goodsId: '辛娜琳',
    bgIMG: '/type/辛娜琳.png',
    title: '辛娜琳',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/辛娜琳@98.png',
  },
  {
    goodsId: '徐雅',
    bgIMG: '/type/徐雅.png',
    title: '徐雅',
    price: 98,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/徐雅@98.png',
  },
  {
    goodsId: '叶琳',
    bgIMG: '/type/叶琳.png',
    title: '叶琳',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/叶琳@98.png',
  },
  {
    goodsId: '圆圆',
    bgIMG: '/type/圆圆.png',
    title: '圆圆',
    price: 98,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/圆圆@98.png',
  },
  {
    goodsId: '智贤',
    bgIMG: '/type/智贤.png',
    title: '智贤',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/智贤@98.png',
  },
  {
    goodsId: 'golaniyule0',
    bgIMG: '/type/golaniyule0.png',
    title: 'golaniyule0',
    price: 98,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/golaniyule0@98.png',
  },
  {
    goodsId: '冬天',
    bgIMG: '/type/冬天.png',
    title: '冬天',
    price: 95,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/冬天@95.png',
  },
  {
    goodsId: '呆梦',
    bgIMG: '/type/呆梦.png',
    title: '呆梦',
    price: 168,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/呆梦@168.png',
  },
  {
    goodsId: '韩璐',
    bgIMG: '/type/韩璐.png',
    title: '韩璐',
    price: 158,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/韩璐@158.png',
  },
  {
    goodsId: '兰',
    bgIMG: '/type/兰.png',
    title: '兰',
    price: 158,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/兰@158.png',
  },
  {
    goodsId: '雷颖',
    bgIMG: '/type/雷颖.png',
    title: '雷颖',
    price: 158,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/雷颖@158.png',
  },
  {
    goodsId: '帕卡',
    bgIMG: '/type/帕卡.png',
    title: '帕卡',
    price: 158,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/帕卡@158.png',
  },
  {
    goodsId: '尤娜',
    bgIMG: '/type/尤娜.png',
    title: '尤娜',
    price: 158,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/尤娜@158.png',
  },
  {
    goodsId: '阿丽莎',
    bgIMG: '/type/阿丽莎.png',
    title: '阿丽莎',
    price: 138,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/阿丽莎@138.png',
  },
  {
    goodsId: '在熙',
    bgIMG: '/type/在熙.png',
    title: '在熙',
    price: 128,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/在熙@128.png',
  },
  {
    goodsId: '朵拉',
    bgIMG: '/type/朵拉.png',
    title: '朵拉',
    price: 90,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/朵拉@90.png',
  },
  {
    goodsId: '芭比昂',
    bgIMG: '/type/芭比昂.png',
    title: '芭比昂',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/芭比昂@88.png',
  },
  {
    goodsId: '芭比基尼',
    bgIMG: '/type/芭比基尼.png',
    title: '芭比基尼',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/芭比基尼@88.png',
  },
  {
    goodsId: '蔡京',
    bgIMG: '/type/蔡京.png',
    title: '蔡京',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/蔡京@88.png',
  },
  {
    goodsId: '蔡时雅',
    bgIMG: '/type/蔡时雅.png',
    title: '蔡时雅',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/蔡时雅@88.png',
  },
  {
    goodsId: '海恩',
    bgIMG: '/type/海恩.png',
    title: '海恩',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/海恩@88.png',
  },
  {
    goodsId: '花井',
    bgIMG: '/type/花井.png',
    title: '花井',
    price: 88,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/花井@88.png',
  },
  {
    goodsId: '雷彬',
    bgIMG: '/type/雷彬.png',
    title: '雷彬',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/雷彬@88.png',
  },
  {
    goodsId: '玫瑰',
    bgIMG: '/type/玫瑰.png',
    title: '玫瑰',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/玫瑰@88.png',
  },
  {
    goodsId: '世京',
    bgIMG: '/type/世京.png',
    title: '世京',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/世京@88.png',
  },
  {
    goodsId: '苏吉',
    bgIMG: '/type/苏吉.png',
    title: '苏吉',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/苏吉@88.png',
  },
  {
    goodsId: '孙铭',
    bgIMG: '/type/孙铭.png',
    title: '孙铭',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/孙铭@88.png',
  },
  {
    goodsId: '塔米米',
    bgIMG: '/type/塔米米.png',
    title: '塔米米',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/塔米米@88.png',
  },
  {
    goodsId: '夏艺拉',
    bgIMG: '/type/夏艺拉.png',
    title: '夏艺拉',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/夏艺拉@88.png',
  },
  {
    goodsId: '徐婉',
    bgIMG: '/type/徐婉.png',
    title: '徐婉',
    price: 88,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/徐婉@88.png',
  },
  {
    goodsId: '艺珠',
    bgIMG: '/type/艺珠.png',
    title: '艺珠',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/艺珠@88.png',
  },
  {
    goodsId: '尹知予',
    bgIMG: '/type/尹知予.png',
    title: '尹知予',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/尹知予@88.png',
  },
  {
    goodsId: '智媛',
    bgIMG: '/type/智媛.png',
    title: '智媛',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/智媛@88.png',
  },
  {
    goodsId: 'haumpah',
    bgIMG: '/type/haumpah.png',
    title: 'haumpah',
    price: 88,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/haumpah@88.png',
  },
  {
    goodsId: '蒂尔',
    bgIMG: '/type/蒂尔.png',
    title: '蒂尔',
    price: 80,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/蒂尔@80.png',
  },
  {
    goodsId: '闵骚',
    bgIMG: '/type/闵骚.png',
    title: '闵骚',
    price: 80,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/闵骚@80.png',
  },
  {
    goodsId: '阿允',
    bgIMG: '/type/阿允.png',
    title: '阿允',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/阿允@78.png',
  },
  {
    goodsId: '白河',
    bgIMG: '/type/白河.png',
    title: '白河',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/白河@78.png',
  },
  {
    goodsId: '薄荷',
    bgIMG: '/type/薄荷.png',
    title: '薄荷',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/薄荷@78.png',
  },
  {
    goodsId: '董顾苒',
    bgIMG: '/type/董顾苒.png',
    title: '董顾苒',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/董顾苒@78.png',
  },
  {
    goodsId: '甘东兰',
    bgIMG: '/type/甘东兰.png',
    title: '甘东兰',
    price: 78,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/甘东兰@78.png',
  },
  {
    goodsId: '高慧智',
    bgIMG: '/type/高慧智.png',
    title: '高慧智',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/高慧智@78.png',
  },
  {
    goodsId: '韩雪',
    bgIMG: '/type/韩雪.png',
    title: '韩雪',
    price: 78,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/韩雪@78.png',
  },
  {
    goodsId: '河正宇',
    bgIMG: '/type/河正宇.png',
    title: '河正宇',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/河正宇@78.png',
  },
  {
    goodsId: '慧智',
    bgIMG: '/type/慧智.png',
    title: '慧智',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/慧智@78.png',
  },
  {
    goodsId: '简芭比',
    bgIMG: '/type/简芭比.png',
    title: '简芭比',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/简芭比@78.png',
  },
  {
    goodsId: '金诗媛',
    bgIMG: '/type/金诗媛.png',
    title: '金诗媛',
    price: 78,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/金诗媛@78.png',
  },
  {
    goodsId: '拉凡',
    bgIMG: '/type/拉凡.png',
    title: '拉凡',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/拉凡@78.png',
  },
  {
    goodsId: '猫猫',
    bgIMG: '/type/猫猫.png',
    title: '猫猫',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/猫猫@78.png',
  },
  {
    goodsId: '米朵',
    bgIMG: '/type/米朵.png',
    title: '米朵',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/米朵@78.png',
  },
  {
    goodsId: '摩卡',
    bgIMG: '/type/摩卡.png',
    title: '摩卡',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/摩卡@78.png',
  },
  {
    goodsId: '皮丘',
    bgIMG: '/type/皮丘.png',
    title: '皮丘',
    price: 78,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/皮丘@78.png',
  },
  {
    goodsId: '朴珍雅',
    bgIMG: '/type/朴珍雅.png',
    title: '朴珍雅',
    price: 78,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/朴珍雅@78.png',
  },
  {
    goodsId: '邱珍',
    bgIMG: '/type/邱珍.png',
    title: '邱珍',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/邱珍@78.png',
  },
  {
    goodsId: '软画',
    bgIMG: '/type/软画.png',
    title: '软画',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/软画@78.png',
  },
  {
    goodsId: '升雅',
    bgIMG: '/type/升雅.png',
    title: '升雅',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/升雅@78.png',
  },
  {
    goodsId: '苏希',
    bgIMG: '/type/苏希.png',
    title: '苏希',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/苏希@78.png',
  },
  {
    goodsId: '泰熙',
    bgIMG: '/type/泰熙.png',
    title: '泰熙',
    price: 78,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/泰熙@78.png',
  },
  {
    goodsId: '尤彩琳',
    bgIMG: '/type/尤彩琳.png',
    title: '尤彩琳',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/尤彩琳@78.png',
  },
  {
    goodsId: 'Muse',
    bgIMG: '/type/Muse.png',
    title: 'Muse',
    price: 78,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/Muse@78.png',
  },
  {
    goodsId: '耶迪',
    bgIMG: '/type/耶迪.png',
    title: '耶迪',
    price: 75,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/耶迪@75.png',
  },
  {
    goodsId: '宝青',
    bgIMG: '/type/宝青.png',
    title: '宝青',
    price: 70,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/宝青@70.png',
  },
  {
    goodsId: '丹独',
    bgIMG: '/type/丹独.png',
    title: '丹独',
    price: 70,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/丹独@70.png',
  },
  {
    goodsId: '多恩',
    bgIMG: '/type/多恩.png',
    title: '多恩',
    price: 70,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/多恩@70.png',
  },
  {
    goodsId: '多妍',
    bgIMG: '/type/多妍.png',
    title: '多妍',
    price: 70,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/多妍@70.png',
  },
  {
    goodsId: '韩智娜',
    bgIMG: '/type/韩智娜.png',
    title: '韩智娜',
    price: 70,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/韩智娜@70.png',
  },
  {
    goodsId: '江陶',
    bgIMG: '/type/江陶.png',
    title: '江陶',
    price: 70,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/江陶@70.png',
  },
  {
    goodsId: '金娜美',
    bgIMG: '/type/金娜美.png',
    title: '金娜美',
    price: 70,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/金娜美@70.png',
  },
  {
    goodsId: '柳迪',
    bgIMG: '/type/柳迪.png',
    title: '柳迪',
    price: 70,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/柳迪@70.png',
  },
  {
    goodsId: '露水',
    bgIMG: '/type/露水.png',
    title: '露水',
    price: 70,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/露水@70.png',
  },
  {
    goodsId: '罗夏',
    bgIMG: '/type/罗夏.png',
    title: '罗夏',
    price: 70,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/罗夏@70.png',
  },
  {
    goodsId: '赛拉',
    bgIMG: '/type/赛拉.png',
    title: '赛拉',
    price: 70,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/赛拉@70.png',
  },
  {
    goodsId: '苏打',
    bgIMG: '/type/苏打.png',
    title: '苏打',
    price: 70,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/苏打@70.png',
  },
  {
    goodsId: '苏麟',
    bgIMG: '/type/苏麟.png',
    title: '苏麟',
    price: 70,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/苏麟@70.png',
  },
  {
    goodsId: '楚民',
    bgIMG: '/type/楚民.png',
    title: '楚民',
    price: 68,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/楚民@68.png',
  },
  {
    goodsId: '哈尼尼',
    bgIMG: '/type/哈尼尼.png',
    title: '哈尼尼',
    price: 68,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/哈尼尼@68.png',
  },
  {
    goodsId: '韩斗妮',
    bgIMG: '/type/韩斗妮.png',
    title: '韩斗妮',
    price: 68,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/韩斗妮@68.png',
  },
  {
    goodsId: '韩京',
    bgIMG: '/type/韩京.png',
    title: '韩京',
    price: 68,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/韩京@68.png',
  },
  {
    goodsId: '环空',
    bgIMG: '/type/环空.png',
    title: '环空',
    price: 68,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/环空@68.png',
  },
  {
    goodsId: '明楚',
    bgIMG: '/type/明楚.png',
    title: '明楚',
    price: 68,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/明楚@68.png',
  },
  {
    goodsId: '熙亚',
    bgIMG: '/type/熙亚.png',
    title: '熙亚',
    price: 68,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/熙亚@68.png',
  },
  {
    goodsId: '徐静',
    bgIMG: '/type/徐静.png',
    title: '徐静',
    price: 68,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/徐静@68.png',
  },
  {
    goodsId: 'a124',
    bgIMG: '/type/a124.png',
    title: 'a124',
    price: 68,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/a124@68.png',
  },
  {
    goodsId: '朱迪',
    bgIMG: '/type/朱迪.png',
    title: '朱迪',
    price: 65,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/朱迪@65.png',
  },
  {
    goodsId: '阿英',
    bgIMG: '/type/阿英.png',
    title: '阿英',
    price: 60,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/阿英@60.png',
  },
  {
    goodsId: '露露',
    bgIMG: '/type/露露.png',
    title: '露露',
    price: 60,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/露露@60.png',
  },
  {
    goodsId: '苏芮',
    bgIMG: '/type/苏芮.png',
    title: '苏芮',
    price: 60,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/苏芮@60.png',
  },
  {
    goodsId: '姚元',
    bgIMG: '/type/姚元.png',
    title: '姚元',
    price: 60,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/姚元@60.png',
  },
  {
    goodsId: '爱迪林',
    bgIMG: '/type/爱迪林.png',
    title: '爱迪林',
    price: 58,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/爱迪林@58.png',
  },
  {
    goodsId: '白雅珍',
    bgIMG: '/type/白雅珍.png',
    title: '白雅珍',
    price: 58,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/白雅珍@58.png',
  },
  {
    goodsId: '曦朵',
    bgIMG: '/type/曦朵.png',
    title: '曦朵',
    price: 58,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/曦朵@58.png',
  },
  {
    goodsId: '新世露',
    bgIMG: '/type/新世露.png',
    title: '新世露',
    price: 55,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/新世露@55.png',
  },
  {
    goodsId: '尹瑟',
    bgIMG: '/type/尹瑟.png',
    title: '尹瑟',
    price: 55,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/尹瑟@55.png',
  },
  {
    goodsId: '布丽',
    bgIMG: '/type/布丽.png',
    title: '布丽',
    price: 50,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/布丽@50.png',
  },
  {
    goodsId: '谷秀真',
    bgIMG: '/type/谷秀真.png',
    title: '谷秀真',
    price: 50,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/谷秀真@50.png',
  },
  {
    goodsId: '海',
    bgIMG: '/type/海.png',
    title: '海',
    price: 50,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/海@50.png',
  },
  {
    goodsId: '河恩',
    bgIMG: '/type/河恩.png',
    title: '河恩',
    price: 50,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/河恩@50.png',
  },
  {
    goodsId: '李秀彬',
    bgIMG: '/type/李秀彬.png',
    title: '李秀彬',
    price: 50,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/李秀彬@50.png',
  },
  {
    goodsId: '莎莎',
    bgIMG: '/type/莎莎.png',
    title: '莎莎',
    price: 50,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/莎莎@50.png',
  },
  {
    goodsId: '刑英',
    bgIMG: '/type/刑英.png',
    title: '刑英',
    price: 50,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/刑英@50.png',
  },
  {
    goodsId: '尤希',
    bgIMG: '/type/尤希.png',
    title: '尤希',
    price: 50,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/尤希@50.png',
  },
  {
    goodsId: '窦熙',
    bgIMG: '/type/窦熙.png',
    title: '窦熙',
    price: 45,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/窦熙@45.png',
  },
  {
    goodsId: '加赛熙',
    bgIMG: '/type/加赛熙.png',
    title: '加赛熙',
    price: 45,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/加赛熙@45.png',
  },
  {
    goodsId: '苏凌',
    bgIMG: '/type/苏凌.png',
    title: '苏凌',
    price: 45,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/苏凌@45.png',
  },
  {
    goodsId: '艺童',
    bgIMG: '/type/艺童.png',
    title: '艺童',
    price: 45,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/艺童@45.png',
  },
  {
    goodsId: 'qkskek',
    bgIMG: '/type/qkskek.png',
    title: 'qkskek',
    price: 45,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/qkskek@45.png',
  },
  {
    goodsId: 'Soi',
    bgIMG: '/type/Soi.png',
    title: 'Soi',
    price: 45,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/Soi@45.png',
  },
  {
    goodsId: 'eerttyui',
    bgIMG: '/type/eerttyui.png',
    title: 'eerttyui',
    price: 45,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/eerttyui@45.png',
  },
  {
    goodsId: 'askl',
    bgIMG: '/type/askl.png',
    title: 'askl',
    price: 40,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/askl@40.png',
  },
  {
    goodsId: '沈清怡',
    bgIMG: '/type/沈清怡.png',
    title: '沈清怡',
    price: 40,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/沈清怡@40.png',
  },
  {
    goodsId: 'a77',
    bgIMG: '/type/a77.png',
    title: 'a77',
    price: 40,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/a77@40.png',
  },
  {
    goodsId: '贝比',
    bgIMG: '/type/贝比.png',
    title: '贝比',
    price: 40,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/贝比@40.png',
  },
  {
    goodsId: '拉雅',
    bgIMG: '/type/拉雅.png',
    title: '拉雅',
    price: 40,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/拉雅@40.png',
  },
  {
    goodsId: '柳月怡',
    bgIMG: '/type/柳月怡.png',
    title: '柳月怡',
    price: 40,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/柳月怡@40.png',
  },
  {
    goodsId: '晴天',
    bgIMG: '/type/晴天.png',
    title: '晴天',
    price: 40,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/晴天@40.png',
  },
  {
    goodsId: '天熙',
    bgIMG: '/type/天熙.png',
    title: '天熙',
    price: 40,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/天熙@40.png',
  },
  {
    goodsId: '智妍',
    bgIMG: '/type/智妍.png',
    title: '智妍',
    price: 40,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/智妍@40.png',
  },
  {
    goodsId: 'hayulll',
    bgIMG: '/type/hayulll.png',
    title: 'hayulll',
    price: 40,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/hayulll@40.png',
  },
  {
    goodsId: 'Rather',
    bgIMG: '/type/Rather.png',
    title: 'Rather',
    price: 40,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/Rather@40.png',
  },
  {
    goodsId: '1004ysus',
    bgIMG: '/type/1004ysus.png',
    title: '1004ysus',
    price: 35,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/1004ysus@35.png',
  },
  {
    goodsId: 'yunhee',
    bgIMG: '/type/yunhee.png',
    title: 'yunhee',
    price: 35,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/yunhee@35.png',
  },
  {
    goodsId: '草草',
    bgIMG: '/type/草草.png',
    title: '草草',
    price: 35,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/草草@35.png',
  },
  {
    goodsId: '灿熙',
    bgIMG: '/type/灿熙.png',
    title: '灿熙',
    price: 35,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/灿熙@35.png',
  },
  {
    goodsId: '多燕',
    bgIMG: '/type/多燕.png',
    title: '多燕',
    price: 35,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/多燕@35.png',
  },
  {
    goodsId: '幂幂',
    bgIMG: '/type/幂幂.png',
    title: '幂幂',
    price: 35,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/幂幂@35.png',
  },
  {
    goodsId: '图雅',
    bgIMG: '/type/图雅.png',
    title: '图雅',
    price: 35,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/图雅@35.png',
  },
  {
    goodsId: '秀丽',
    bgIMG: '/type/秀丽.png',
    title: '秀丽',
    price: 35,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/秀丽@35.png',
  },
  {
    goodsId: '尹英瑞',
    bgIMG: '/type/尹英瑞.png',
    title: '尹英瑞',
    price: 30,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/尹英瑞@30.png',
  },
  {
    goodsId: 'ayo111',
    bgIMG: '/type/ayo111.png',
    title: 'ayo111',
    price: 30,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/ayo111@30.png',
  },
  {
    goodsId: 'poqwe',
    bgIMG: '/type/poqwe.png',
    title: 'poqwe',
    price: 30,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/poqwe@30.png',
  },
  {
    goodsId: '柳雪儿',
    bgIMG: '/type/柳雪儿.png',
    title: '柳雪儿',
    price: 30,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/柳雪儿@30.png',
  },
  {
    goodsId: '露西',
    bgIMG: '/type/露西.png',
    title: '露西',
    price: 30,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/露西@30.png',
  },
  {
    goodsId: 'Guyl',
    bgIMG: '/type/Guyl.png',
    title: 'Guyl',
    price: 30,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/Guyl@30.png',
  },
  {
    goodsId: '2do2do',
    bgIMG: '/type/2do2do.png',
    title: '2do2do',
    price: 25,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/2do2do@25.png',
  },
  {
    goodsId: '阿孝',
    bgIMG: '/type/阿孝.png',
    title: '阿孝',
    price: 25,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/阿孝@25.png',
  },
  {
    goodsId: '素婉',
    bgIMG: '/type/素婉.png',
    title: '素婉',
    price: 25,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/素婉@25.png',
  },
  {
    goodsId: 'gpgp',
    bgIMG: '/type/gpgp.png',
    title: 'gpgp',
    price: 20,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/gpgp@20.png',
  },
  {
    goodsId: '尹玛乔',
    bgIMG: '/type/尹玛乔.png',
    title: '尹玛乔',
    price: 20,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/尹玛乔@20.png',
  },
  {
    goodsId: '何妍珠',
    bgIMG: '/type/何妍珠.png',
    title: '何妍珠',
    price: 20,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/何妍珠@20.png',
  },
  {
    goodsId: '鹿小姐',
    bgIMG: '/type/鹿小姐.png',
    title: '鹿小姐',
    price: 20,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/鹿小姐@20.png',
  },
  {
    goodsId: '尼莫',
    bgIMG: '/type/尼莫.png',
    title: '尼莫',
    price: 20,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/尼莫@20.png',
  },
  {
    goodsId: '素颖',
    bgIMG: '/type/素颖.png',
    title: '素颖',
    price: 20,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/素颖@20.png',
  },
  {
    goodsId: 'Luan',
    bgIMG: '/type/Luan.png',
    title: 'Luan',
    price: 15,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/Luan@15.png',
  },
  {
    goodsId: 'gpflad',
    bgIMG: '/type/gpflad.png',
    title: 'gpflad',
    price: 15,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/gpflad@15.png',
  },
  {
    goodsId: '蔡丽',
    bgIMG: '/type/蔡丽.png',
    title: '蔡丽',
    price: 15,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/蔡丽@15.png',
  },
  {
    goodsId: '玛丽',
    bgIMG: '/type/玛丽.png',
    title: '玛丽',
    price: 15,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/玛丽@15.png',
  },
  {
    goodsId: '米蒂',
    bgIMG: '/type/米蒂.png',
    title: '米蒂',
    price: 15,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/米蒂@15.png',
  },
  {
    goodsId: '叶璃',
    bgIMG: '/type/叶璃.png',
    title: '叶璃',
    price: 15,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/叶璃@15.png',
  },
  {
    goodsId: 'Saebom',
    bgIMG: '/type/Saebom.png',
    title: 'Saebom',
    price: 15,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/Saebom@15.png',
  },
  {
    goodsId: 'ooeeejj',
    bgIMG: '/type/ooeeejj.png',
    title: 'ooeeejj',
    price: 10,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/ooeeejj@10.png',
  },
  {
    goodsId: 'ych',
    bgIMG: '/type/ych.png',
    title: 'ych',
    price: 10,
    allowUpdate: true,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/ych@10.png',
  },
  {
    goodsId: 'godlita',
    bgIMG: '/type/godlita.png',
    title: 'godlita',
    price: 10,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/godlita@10.png',
  },
  {
    goodsId: '艾文',
    bgIMG: '/type/艾文.png',
    title: '艾文',
    price: 10,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/艾文@10.png',
  },
  {
    goodsId: '金瑟姬',
    bgIMG: '/type/金瑟姬.png',
    title: '金瑟姬',
    price: 10,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/金瑟姬@10.png',
  },
  {
    goodsId: '莉雅',
    bgIMG: '/type/莉雅.png',
    title: '莉雅',
    price: 10,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/莉雅@10.png',
  },
  {
    goodsId: '敏彩',
    bgIMG: '/type/敏彩.png',
    title: '敏彩',
    price: 10,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/敏彩@10.png',
  },
  {
    goodsId: '娜比',
    bgIMG: '/type/娜比.png',
    title: '娜比',
    price: 10,
    allowUpdate: false,
    originalPprice: 888,
    year: 'anchor',
    detailImg: '/typeGoods/娜比@10.png',
  },
]
