export const avatarPrices = {
  不良人: 6.6,
  少年歌行: 6.6,
  斯莱特林: 6.6,
  碧蓝航线: 6.6,
  巅峰荣耀: 6.6,
  中野二乃: 6.6,
  至尊戒: 6.6,
  大王不高兴: 6.6,
  精灵王: 6.6,
  格兰芬多: 6.6,
  拳皇: 6.6,
  梦100: 6.6,
  赫奇帕奇: 6.6,
  拉文克劳: 6.6,
  择天记: 6.6,
  异常生物: 6.6,
  灵笼: 6.6,
  快把我哥带走: 6.6,
  记忆U盘: 6.6,
  全职高手: 6.6,
  黑白无双: 6.6,
  梦塔雪谜城: 6.6,
  碧蓝之海: 6.6,
  中野四叶: 6.6,
  纳米核心: 6.6,
  万界仙踪: 6.6,
  请吃红小豆: 6.6,
  公主连结可可萝: 6.6,
  沈剑心: 6.6,
  不吉波普不笑: 6.6,
  春原庄的管理人小姐: 6.6,
  汉化日记: 6.6,
  喂看见耳朵啦: 6.6,
  公主连结佩可莉姆: 6.6,
  工作细胞: 6.6,
  血色苍穹: 6.6,
  凹凸世界: 6.6,
  圣诞节快乐: 6.6,
  王子碰碰球: 6.6,
  中野一花: 6.6,
  画江湖之侠岚: 6.6,
  萌妻食神: 6.6,
  平安物语: 6.6,
  斗破苍穹: 6.6,
  地中海: 6.6,
  刀说异数: 6.6,
  少女前线: 6.6,
  茶啊二中: 6.6,
  我家大师兄脑子有坑: 6.6,
  暮光幻影: 6.6,
  中野三玖: 6.6,
  InfiniTForce: 6.6,
  拾又之国: 6.6,
  天谕: 6.6,
  刺客伍六七: 6.6,
  公主连结凯露: 6.6,
  citrus: 6.6,
  中野五月: 6.6,
  斩兽之刃: 6.6,
  领风者: 6.6,
}

export const avatarFramesMap = new Map<string, { price: number; name: string }>(
  [
    ['斩兽之刃', { price: avatarPrices['斩兽之刃'], name: '斩兽之刃' }],
    ['不良人', { price: avatarPrices['不良人'], name: '不良人' }],
    ['少年歌行', { price: avatarPrices['少年歌行'], name: '少年歌行' }],
    ['斯莱特林', { price: avatarPrices['斯莱特林'], name: '斯莱特林' }],
    ['碧蓝航线', { price: avatarPrices['碧蓝航线'], name: '碧蓝航线' }],
    ['巅峰荣耀', { price: avatarPrices['巅峰荣耀'], name: '巅峰荣耀' }],
    ['中野二乃', { price: avatarPrices['中野二乃'], name: '中野二乃' }],
    ['至尊戒', { price: avatarPrices['至尊戒'], name: '至尊戒' }],
    ['大王不高兴', { price: avatarPrices['大王不高兴'], name: '大王不高兴' }],
    ['精灵王', { price: avatarPrices['精灵王'], name: '精灵王' }],
    ['格兰芬多', { price: avatarPrices['格兰芬多'], name: '格兰芬多' }],
    ['拳皇', { price: avatarPrices['拳皇'], name: '拳皇' }],
    ['梦100', { price: avatarPrices['梦100'], name: '梦100' }],
    ['赫奇帕奇', { price: avatarPrices['赫奇帕奇'], name: '赫奇帕奇' }],
    ['拉文克劳', { price: avatarPrices['拉文克劳'], name: '拉文克劳' }],
    ['择天记', { price: avatarPrices['择天记'], name: '择天记' }],
    ['异常生物', { price: avatarPrices['异常生物'], name: '异常生物' }],
    ['灵笼', { price: avatarPrices['灵笼'], name: '灵笼' }],
    [
      '快把我哥带走',
      { price: avatarPrices['快把我哥带走'], name: '快把我哥带走' },
    ],
    ['记忆U盘', { price: avatarPrices['记忆U盘'], name: '记忆U盘' }],
    ['全职高手', { price: avatarPrices['全职高手'], name: '全职高手' }],
    ['黑白无双', { price: avatarPrices['黑白无双'], name: '黑白无双' }],
    ['梦塔雪谜城', { price: avatarPrices['梦塔雪谜城'], name: '梦塔雪谜城' }],
    ['碧蓝之海', { price: avatarPrices['碧蓝之海'], name: '碧蓝之海' }],
    ['中野四叶', { price: avatarPrices['中野四叶'], name: '中野四叶' }],
    ['纳米核心', { price: avatarPrices['纳米核心'], name: '纳米核心' }],
    ['万界仙踪', { price: avatarPrices['万界仙踪'], name: '万界仙踪' }],
    ['请吃红小豆', { price: avatarPrices['请吃红小豆'], name: '请吃红小豆' }],
    [
      '公主连结可可萝',
      { price: avatarPrices['公主连结可可萝'], name: '公主连结可可萝' },
    ],
    ['沈剑心', { price: avatarPrices['沈剑心'], name: '沈剑心' }],
    [
      '不吉波普不笑',
      { price: avatarPrices['不吉波普不笑'], name: '不吉波普不笑' },
    ],
    [
      '春原庄的管理人小姐',
      { price: avatarPrices['春原庄的管理人小姐'], name: '春原庄的管理人小姐' },
    ],
    ['汉化日记', { price: avatarPrices['汉化日记'], name: '汉化日记' }],
    [
      '喂看见耳朵啦',
      { price: avatarPrices['喂看见耳朵啦'], name: '喂看见耳朵啦' },
    ],
    [
      '公主连结佩可莉姆',
      { price: avatarPrices['公主连结佩可莉姆'], name: '公主连结佩可莉姆' },
    ],
    ['工作细胞', { price: avatarPrices['工作细胞'], name: '工作细胞' }],
    ['血色苍穹', { price: avatarPrices['血色苍穹'], name: '血色苍穹' }],
    ['凹凸世界', { price: avatarPrices['凹凸世界'], name: '凹凸世界' }],
    ['圣诞节快乐', { price: avatarPrices['圣诞节快乐'], name: '圣诞节快乐' }],
    ['王子碰碰球', { price: avatarPrices['王子碰碰球'], name: '王子碰碰球' }],
    ['中野一花', { price: avatarPrices['中野一花'], name: '中野一花' }],
    [
      '画江湖之侠岚',
      { price: avatarPrices['画江湖之侠岚'], name: '画江湖之侠岚' },
    ],
    ['萌妻食神', { price: avatarPrices['萌妻食神'], name: '萌妻食神' }],
    ['平安物语', { price: avatarPrices['平安物语'], name: '平安物语' }],
    ['斗破苍穹', { price: avatarPrices['斗破苍穹'], name: '斗破苍穹' }],
    ['地中海', { price: avatarPrices['地中海'], name: '地中海' }],
    ['刀说异数', { price: avatarPrices['刀说异数'], name: '刀说异数' }],
    ['少女前线', { price: avatarPrices['少女前线'], name: '少女前线' }],
    ['茶啊二中', { price: avatarPrices['茶啊二中'], name: '茶啊二中' }],
    [
      '我家大师兄脑子有坑',
      { price: avatarPrices['我家大师兄脑子有坑'], name: '我家大师兄脑子有坑' },
    ],
    ['暮光幻影', { price: avatarPrices['暮光幻影'], name: '暮光幻影' }],
    ['中野三玖', { price: avatarPrices['中野三玖'], name: '中野三玖' }],
    [
      'InfiniTForce',
      { price: avatarPrices['InfiniTForce'], name: 'InfiniTForce' },
    ],
    ['拾又之国', { price: avatarPrices['拾又之国'], name: '拾又之国' }],
    ['天谕', { price: avatarPrices['天谕'], name: '天谕' }],
    ['刺客伍六七', { price: avatarPrices['刺客伍六七'], name: '刺客伍六七' }],
    [
      '公主连结凯露',
      { price: avatarPrices['公主连结凯露'], name: '公主连结凯露' },
    ],
    ['citrus', { price: avatarPrices['citrus'], name: 'citrus' }],
    ['中野五月', { price: avatarPrices['中野五月'], name: '中野五月' }],
    ['领风者', { price: avatarPrices['领风者'], name: '领风者' }],
  ],
)
export const goodsMap = new Map<
  string,
  { price: number; days: number; name: string }
>([
  ['vip_31', { price: 299, days: 31, name: 'VIP月卡会员' }],
  ['vip_93', { price: 799, days: 93, name: 'VIP季卡会员' }],
  ['vip_366', { price: 2499, days: 366, name: 'VIP年卡会员' }],
  ['vip_1098', { price: 4999, days: 999999, name: 'VIP永久卡会员' }],
  // ['vip_1098', { price: 4999, days: 1098, name: 'VIP三年卡会员' }],
])
